# Generated by Django 5.1.2 on 2024-11-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDetalles',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('imagen_url', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'detalles_usuario',
            },
        ),
    ]
