# Generated by Django 5.1.2 on 2024-11-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuariodetalles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficio', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('experiencia_laboral', models.PositiveIntegerField()),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'perfil_laboral',
            },
        ),
        migrations.RemoveField(
            model_name='usuariodetalles',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='usuariodetalles',
            name='password',
            field=models.CharField(default='default_password', max_length=255),
        ),
        migrations.AddField(
            model_name='usuariodetalles',
            name='telefono',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuariodetalles',
            name='correo',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuariodetalles',
            name='imagen_url',
            field=models.URLField(max_length=255),
        ),
    ]
