# Generated by Django 5.1.2 on 2024-11-05 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_perfillaboral_remove_usuariodetalles_contraseña_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilLaboral',
        ),
        migrations.DeleteModel(
            name='UsuarioDetalles',
        ),
    ]
