# Generated by Django 5.1.2 on 2024-11-05 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_perfillaboral_usuariodetalles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('trabajador', models.ForeignKey(limit_choices_to={'tipo_usuario': 'TRABAJADOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad', to='api.usuarios')),
            ],
            options={
                'db_table': 'disponibilidad',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('trabajador', models.ForeignKey(limit_choices_to={'tipo_usuario': 'TRABAJADOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='api.usuarios')),
            ],
            options={
                'db_table': 'habilidades',
            },
        ),
    ]
